### ISSUE TITLE
some simplemobs are immortal

### ISSUE THREAD

**Issue by deltanedas** [Goob-Station/Goob-Station#2730]
they never die

verified to be immortal:
- goliath
- icewing watcher specifically

NOT immortal:
- carp
- hivelords
- watchers

**Comment by SkippyMcSkips** [comment]
Blobbernauts are immortal, and Borgs don't take most types of damage

**Comment by pheenty** [comment]
fixed i think?

**Comment by gluesniffler** [comment]
no it is not fixed, as of now:

- blobbernauts become immortal at an undeterminate distance from blob (allegedly)
- polymorphed humans

are immortal too

**Comment by Roudenn** [comment]
@gluesniffler is this fake?

**Comment by SkippyMcSkips** [comment]
This is fixed as far as I can tell.
