### ISSUE TITLE
Meat Tendons can gasp

### ISSUE THREAD

**Issue by SkippyMcSkips** [Goob-Station/Goob-Station#4441]
<img width="604" height="440" alt="Image" src="https://github.com/user-attachments/assets/530ec1f1-3b0e-4708-9b68-cb0da2baa2c5" />

Now I've seen everything...

**Comment by XWasHere** [comment]
it looks like this is an upstream bug https://github.com/space-wizards/space-station-14/issues/38900

**Comment by SkippyMcSkips** [comment]
> it looks like this is an upstream bug [space-wizards/space-station-14#38900](https://github.com/space-wizards/space-station-14/issues/38900)

Good find!

Looks like it was fixed by https://github.com/space-wizards/space-station-14/pull/38911 on July 17th, so it should have been included in our most recent July 20th upstream, but it wasn't. Maybe could be cherry-picked or included in the next one?

**Comment by XWasHere** [comment]
it looks like the only thing that pr fixed was it spamming logs, i checked out the wizden master branch and the bug is still present. at the moment it looks like theres two prs to "fix" it, one that removes respiratorcomponent from the meatzu entirely (it wasnt working at all until a bugfix) and one that makes it intended behavior and makes it happen less

https://github.com/space-wizards/space-station-14/pull/38910
https://github.com/space-wizards/space-station-14/pull/39304

im not sure how 39304 would perform when the station is covered in meatzu, probably not well.

**Comment by SkippyMcSkips** [comment]
> it looks like the only thing that pr fixed was it spamming logs, i checked out the wizden master branch and the bug is still present. at the moment it looks like theres two prs to "fix" it, one that removes respiratorcomponent from the meatzu entirely (it wasnt working at all until a bugfix) and one that makes it intended behavior and makes it happen less
> 
> [space-wizards/space-station-14#38910](https://github.com/space-wizards/space-station-14/pull/38910) [space-wizards/space-station-14#39304](https://github.com/space-wizards/space-station-14/pull/39304)
> 
> im not sure how 39304 would perform when the station is covered in meatzu, probably not well.

Oops, you’re right. I was drunk and misread that PR as saying that it *did* fix the suffocation

**Comment by SkippyMcSkips** [comment]
Closing as this is an upstream issue
